name: Code Quality

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  code-quality:
    name: Code Quality Checks
    uses: ./.github/workflows/_setup-php.yml
    with:
      run-phpcs: true
      run-phpstan: true
      fail-fast: false
