name: Deploy to WordPress.org

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to WordPress.org
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        # actions/checkout@v4
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          persist-credentials: false

      - name: WordPress Plugin Deploy
        id: deploy
        # 10up/action-wordpress-plugin-deploy@stable
        uses: 10up/action-wordpress-plugin-deploy@54bd289b8525fd23a5c365ec369185f2966529c2
        with:
          generate-zip: true
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: wp-performance-wizard

      - name: Upload zip to GitHub Release
        if: github.event_name == 'release'
        # softprops/action-gh-release@v2
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65
        with:
          files: ${{ github.workspace }}/${{ github.event.repository.name }}.zip
