name: PHPStan Static Analysis

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  phpstan:
    name: PHPStan Analysis
    uses: ./.github/workflows/_setup-php.yml
    with:
      run-phpcs: false
      run-phpstan: true
      fail-fast: false
